# Generated by Django 4.1.6 on 2023-02-10 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField(verbose_name='Номер пользователя')),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'webp'])], verbose_name='Фото к комментарию')),
                ('comment_date', models.DateField(verbose_name='Дата комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['comment_date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateField(verbose_name='Когда прислали')),
                ('page_id', models.IntegerField(null=True, verbose_name='Номер страницы')),
                ('name', models.CharField(max_length=50, verbose_name='Заголовок сообщения')),
                ('response', models.URLField(verbose_name='Адрес страницы')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название ингредиента')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название метода')),
                ('description', models.TextField(null=True, verbose_name='Описание метода')),
            ],
            options={
                'verbose_name': 'Метод',
                'verbose_name_plural': 'Методы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Кухня страны')),
                ('description', models.TextField(verbose_name='Описание кухни страны')),
            ],
            options={
                'verbose_name': 'Национальная кухня',
                'verbose_name_plural': 'Национальные кухни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'webp'])], verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Рецепт')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cooking_time', models.TimeField(verbose_name='Время готовки')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1, null=True, verbose_name='Рейтинг')),
                ('number_of_votes', models.IntegerField(null=True, verbose_name='Количество голосов')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество порций')),
                ('info', models.TextField(null=True, verbose_name='Доп. информация')),
                ('valid', models.BooleanField(default=False, verbose_name='Прошло модерацию')),
                ('parced', models.BooleanField(default=False, verbose_name='Получено от парсинга')),
                ('complexity', models.CharField(max_length=40, verbose_name='Сложность готовки')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['name', 'rating'],
            },
        ),
        migrations.CreateModel(
            name='recipe_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Шаг для рецепта',
                'verbose_name_plural': 'Шаги для рецепта',
                'ordering': ['recipe'],
            },
        ),
        migrations.CreateModel(
            name='recipe_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Тэг для рецепта',
                'verbose_name_plural': 'Тэги для рецепта',
                'ordering': ['recipe'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тэга')),
                ('recipe', models.ManyToManyField(through='recipe.recipe_tags', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Номер шага')),
                ('description', models.TextField(verbose_name='Описание шага')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Фотография')),
                ('recipe', models.ManyToManyField(through='recipe.recipe_step', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'Метод',
                'verbose_name_plural': 'Методы',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddField(
            model_name='recipe_tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.tag', verbose_name='Номер тэга'),
        ),
        migrations.AddField(
            model_name='recipe_step',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.step', verbose_name='Номер метода'),
        ),
        migrations.CreateModel(
            name='recipe_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.photo', verbose_name='Номер фото')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Фото для рецепта',
                'verbose_name_plural': 'Фотографии для рецепта',
                'ordering': ['recipe'],
                'unique_together': {('recipe', 'photo')},
            },
        ),
        migrations.CreateModel(
            name='recipe_nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.nation', verbose_name='Номер кухни страны')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт национальной кухни',
                'verbose_name_plural': 'Рецепты национальной кухни',
                'ordering': ['recipe'],
                'unique_together': {('recipe', 'nation')},
            },
        ),
        migrations.CreateModel(
            name='recipe_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.method', verbose_name='Номер метода')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Метод для рецепта',
                'verbose_name_plural': 'Методы для рецепта',
                'ordering': ['recipe'],
                'unique_together': {('recipe', 'method')},
            },
        ),
        migrations.CreateModel(
            name='recipe_ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('volume', models.IntegerField(verbose_name='Количество')),
                ('measure', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient', verbose_name='Номер ингредиента')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Ингредиент для рецепта',
                'verbose_name_plural': 'Ингредиент для рецепта',
                'ordering': ['recipe'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='recipe_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exist', models.BooleanField(verbose_name='Существует')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.comment', verbose_name='Номер коммента')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Комментарий к рецепту',
                'verbose_name_plural': 'Комментарии к рецепту',
                'ordering': ['recipe'],
            },
        ),
        migrations.CreateModel(
            name='recipe_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.category', verbose_name='Номер категории')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Категория для рецепта',
                'verbose_name_plural': 'Категории для рецепта',
                'ordering': ['recipe'],
                'unique_together': {('recipe', 'category')},
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='recipe',
            field=models.ManyToManyField(through='recipe.recipe_photo', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='nation',
            name='recipe',
            field=models.ManyToManyField(through='recipe.recipe_nation', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='method',
            name='recipe',
            field=models.ManyToManyField(through='recipe.recipe_method', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ManyToManyField(through='recipe.recipe_ingredient', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ManyToManyField(through='recipe.recipe_comment', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='category',
            name='recipe',
            field=models.ManyToManyField(through='recipe.recipe_category', to='recipe.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe_tags',
            unique_together={('recipe', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe_step',
            unique_together={('recipe', 'step')},
        ),
        migrations.CreateModel(
            name='ingredient_recipe_alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_third', to='recipe.ingredient', verbose_name='Номер ингредиента')),
                ('ingredient_alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_forth', to='recipe.ingredient', verbose_name='Номер альтернативы ингредиента')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Номер рецепта')),
            ],
            options={
                'verbose_name': 'Ингредиент для замены',
                'verbose_name_plural': 'Ингредиенты для замены',
                'ordering': ['recipe'],
                'unique_together': {('recipe', 'ingredient', 'ingredient_alternative')},
            },
        ),
        migrations.CreateModel(
            name='ingredient_alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exists', models.BooleanField(default=True, verbose_name='Существует')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_first', to='recipe.ingredient', verbose_name='Номер ингредиента')),
                ('ingredient_alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_second', to='recipe.ingredient', verbose_name='Номер альтернативы ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент для замены',
                'verbose_name_plural': 'Ингредиенты для замены',
                'ordering': ['ingredient'],
                'unique_together': {('ingredient', 'ingredient_alternative')},
            },
        ),
    ]
