version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      - ENVIRONMENT=$ENV_MENU
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$.POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    networks:
      - postgres

  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: web
    command: >
      sh -c "python manage.py migrate &&
             gunicorn prostoemenu.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=$ENV_MENU
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$.POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    networks:
      - postgres
      - prostoemenu

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/usr/share/nginx/html/static/
      - media_value:/usr/share/nginx/html/media/
    depends_on:
      - web
    networks:
      - prostoemenu

networks:
  prostoemenu:
    name: prostoemenu
    external: true
  postgres:
    name: postgres
    external: true

volumes:
  db_value:
  static_value:
  media_value: