version: '3.3'

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  web:
    build:
      context: ../back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/:/usr/share/nginx/html/api/docs/
#      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
#      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/usr/share/nginx/html/static/
      - media_value:/usr/share/nginx/html/media/
    depends_on:
      - web

volumes:
  db_value:
  static_value:
  media_value:
