version: '3.9'

services:
  front:
    image: infra-front:3.1.15
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.front
    container_name: front
    ports:
      - "$PORT_NGINX:80"
    volumes:
      - /opt/static_front_data:/usr/share/nginx/html/front/
      - /opt/static_admin_data:/usr/share/nginx/html/static/
      - /opt/media_data:/usr/share/nginx/html/media/
    environment:
      - PORT_NGINX=$PORT_NGINX
      - VITE_API_URL=$VITE_API_URL
      - VITE_IMAGE_URL=$VITE_IMAGE_URL
    networks:
      - prostoemenu

networks:
  prostoemenu:
    name: prostoemenu
    external: true