version: '3.9'

services:
  front:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.front
    container_name: front
    ports:
      - "$PORT_NGINX:80"
    volumes:
      - media_value:/usr/share/nginx/html/media/
    environment:
      - PORT_NGINX=$PORT_NGINX
      - VITE_API_URL=$VITE_API_URL
    networks:
      - prostoemenu

networks:
  prostoemenu:
    name: prostoemenu
    external: true

volumes:
  static_value:
  media_value:
