version: '3.9'

services:
  db:
    restart: always
    container_name: db
    image: postgres:15-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    env_file:
      - ../.env


volumes:
  db_value:
