version: '3.9'

services:
  app:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile2.back
    container_name: app
    command: >
      sh -c "python /back/manage.py migrate &&
             gunicorn prostoemenu.wsgi:application --bind 0.0.0.0:8000 --workers=4"
    restart: always
    environment:
      - ENVIRONMENT=$ENV_MENU
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    volumes:
      - /opt/static_admin_data:/back/static/
      - /opt/media_data:/back/mediafiles/
    networks:
      - postgres
      - prostoemenu

networks:
  prostoemenu:
    name: prostoemenu
    external: true
  postgres:
    name: postgres
    external: true
