version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - /opt/pg_data:/var/lib/postgresql/data/
    environment:
      - ENVIRONMENT=$ENV_MENU
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=postgres
    networks:
      - postgres

networks:
  postgres:
    name: postgres
    external: true