version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      - ENVIRONMENT=$ENV_MENU
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$.POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    networks:
      - postgres

  app:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.back
    container_name: app
    command: >
      sh -c "python /app/manage.py migrate &&
             gunicorn prostoemenu.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=$ENV_MENU
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$.POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    networks:
      - postgres
      - prostoemenu

networks:
  prostoemenu:
    name: prostoemenu
    external: true
  postgres:
    name: postgres
    external: true

volumes:
  db_value:
  static_value:
  media_value: