# Generated by Django 4.1.7 on 2023-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='caiten_task_id',
            field=models.IntegerField(),
        ),
    ]
