# Generated by Django 4.1.7 on 2023-03-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_caiten_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='caiten_task_id',
            field=models.IntegerField(unique=True),
        ),
    ]
