# Generated by Django 4.1.7 on 2023-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_caiten_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
