# Generated by Django 4.1.7 on 2023-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_participant_name_alter_participant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='kaiten_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
