# Generated by Django 4.1.8 on 2023-04-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('kaiten_user_id', models.IntegerField(null=True)),
                ('number_of_completed_tasks', models.IntegerField(default=0)),
                ('last_updated_task', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaiten_task_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=350)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='ParticipantTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaiten.participant', verbose_name='Номер участника')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaiten.task', verbose_name='Номер задания')),
            ],
            options={
                'verbose_name': 'Задание участника',
                'verbose_name_plural': 'Задания участника',
                'unique_together': {('participant', 'task')},
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='task',
            field=models.ManyToManyField(related_name='participant_task', through='kaiten.ParticipantTasks', to='kaiten.task'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('name', 'username')},
        ),
    ]
