# Generated by Django 5.0.2 on 2024-04-05 14:33

import common.validators
import django.core.validators
from django.conf import settings as django_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(500),
                    common.validators.AcceptedSymbolsValidator(
                        django_settings.ACCEPTED_SYMBOLS
                    ),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    common.validators.AcceptedSymbolsValidator(
                        django_settings.ACCEPTED_SYMBOLS
                    ),
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(500),
                    common.validators.AcceptedSymbolsValidator(
                        django_settings.ACCEPTED_SYMBOLS
                    ),
                ],
                verbose_name="Описание шага",
            ),
        ),
    ]
