# Generated by Django 5.0.2 on 2024-04-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_description_alter_recipe_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="image",
            field=models.ImageField(
                null=True, upload_to="recipes", verbose_name="Изображение"
            ),
        ),
    ]
