# Generated by Django 5.0.2 on 2024-05-02 06:15

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_category_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipes", verbose_name="Изображение"
            ),
        ),
    ]
