# Generated by Django 5.0.2 on 2024-05-12 17:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_recipeingredient_volume_alter_recipestep_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="volume",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="Количество",
            ),
        ),
    ]
