# Generated by Django 5.0.2 on 2024-06-25 12:44

import common.validators
import django.core.validators
import recipes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_recipeingredient_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(500),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Без категории",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cover_path",
            field=models.ImageField(
                upload_to=recipes.utils.get_recipe_image_upload_path,
                verbose_name="Главное фото",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(500),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(500),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Описание шага",
            ),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=recipes.utils.get_step_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
    ]
