# Generated by Django 3.2.16 on 2023-01-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230111_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время приготовления в минутах'),
        ),
    ]
