# Generated by Django 3.2.16 on 2023-01-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=36, unique=True, verbose_name='Slug поля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nation',
            name='slug',
            field=models.SlugField(default=1, max_length=36, unique=True, verbose_name='Slug поля'),
            preserve_default=False,
        ),
    ]
