# Generated by Django 3.2.16 on 2023-01-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='user',
        ),
    ]
