# Generated by Django 3.2.16 on 2023-01-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_ingredients_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
    ]
