# Generated by Django 5.0.2 on 2024-06-25 12:44

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="abbreviation",
            field=models.CharField(
                max_length=30,
                validators=[
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    )
                ],
                verbose_name="Аббревиатура",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="name",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Название",
            ),
        ),
    ]
