export const initialTestFormState = {
  currentFormStage: 1,
  recipeName: null,
  recipeComplexity: null,
  servings: 0,
  cookingTime: 0,
  ovenTime: 0,
  description: null,
  finishedPhoto: null,
  ingredients: [{ elementID: 1, name: '', volume: '', measure: 'г' }],
  cookingSteps: [],
  comment: null,
  author: null,
  email: null,
  isLoading: false,
  isError: false,
  isSuccess: false,
  errorMessage: null,
};
export const filledTestFormState = {
  currentFormStage: 1,
  recipeName: 'рецепт борща',
  recipeComplexity: null,
  servings: 0,
  cookingTime: 0,
  ovenTime: 0,
  description: null,
  finishedPhoto: null,
  ingredients: [
    { elementID: 1, name: 'Свекла', volume: '2', measure: 'кг' },
    { elementID: 1, name: 'Капуста белокачанная', volume: '1', measure: 'кг' },
  ],
  cookingSteps: [],
  comment: null,
  author: null,
  email: null,
  isLoading: false,
  isError: false,
  isSuccess: false,
  errorMessage: null,
};
