# Generated by Django 4.1.7 on 2023-04-20 14:07

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=account.models.generate_activation_code, max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activ_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код активации',
                'verbose_name_plural': 'Коды активации',
                'ordering': ('user',),
            },
        ),
    ]
