# Generated by Django 4.1.7 on 2023-08-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_activationcode_code_generated_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activ_code', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
    ]
