# Generated by Django 4.2.4 on 2023-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="sort",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Порядок ингредиента"
            ),
        ),
    ]
