# Generated by Django 4.1.7 on 2023-02-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', through='recipe.RecipeCategories', to='recipe.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, related_name='photos', through='recipe.RecipePhotos', to='recipe.photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='step',
            field=models.ManyToManyField(blank=True, null=True, related_name='steps', through='recipe.RecipeSteps', to='recipe.step'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', through='recipe.RecipeTags', to='recipe.tag'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient_alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_alternative', to='recipe.ingredient', verbose_name='Номер альтернативы'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient_alternative_measure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient_alternative_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
