# Generated by Django 4.1.7 on 2023-03-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together={('recipe', 'ingredient', 'ingredient_alternative')},
        ),
    ]
