# Generated by Django 4.1.7 on 2023-02-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_category_alter_recipe_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(related_name='categories', through='recipe.RecipeCategories', to='recipe.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredients', through='recipe.RecipeIngredients', to='recipe.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ManyToManyField(related_name='photos', through='recipe.RecipePhotos', to='recipe.photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='step',
            field=models.ManyToManyField(related_name='steps', through='recipe.RecipeSteps', to='recipe.step'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='tags', through='recipe.RecipeTags', to='recipe.tag'),
        ),
    ]
