# Generated by Django 4.1.7 on 2023-06-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='volume',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='RecipeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата на главной')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='ID рецепта дня')),
            ],
            options={
                'verbose_name': 'Рецепт дня',
                'verbose_name_plural': 'Рецепты дня',
                'unique_together': {('recipe', 'date')},
            },
        ),
    ]
