# Generated by Django 4.1.7 on 2023-03-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipeingredients_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
