# Generated by Django 4.1.7 on 2023-09-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_measurement_options_and_more'),
        ('recipe', '0003_alter_recipe_options'),
    ]

    operations = [
    ]
