# Generated by Django 4.1.7 on 2023-09-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_merge_20230924_1809'),
        ('recipe', '0004_merge_20230927_0947'),
    ]

    operations = [
    ]
