# Generated by Django 4.1.7 on 2023-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_merge_20230927_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
