# Generated by Django 4.1.7 on 2023-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='complexity',
            field=models.SmallIntegerField(verbose_name='Сложность готовки'),
        ),
        migrations.AlterField(
            model_name='step',
            name='photo',
            field=models.CharField(max_length=100, null=True, verbose_name='Фотография'),
        ),
    ]
