# Generated by Django 4.1.7 on 2023-12-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_complexity_alter_step_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='main_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='recipe.photo', verbose_name='Главное фото'),
        ),
    ]
