# Generated by Django 4.1.7 on 2023-12-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.CharField(default='default_photo.jpg', max_length=100, verbose_name='Путь к фото'),
        ),
    ]
