# Generated by Django 5.0.2 on 2024-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                default="Без категории",
                max_length=100,
                verbose_name="Категория ингредиента",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название ингредиента"),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_ingredient"
            ),
        ),
    ]
