# Generated by Django 5.0.2 on 2024-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingredients",
            "0002_alter_ingredient_category_alter_ingredient_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                default="Без категории", max_length=100, verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="sort",
            field=models.SmallIntegerField(null=True, verbose_name="Порядок"),
        ),
    ]
