# Generated by Django 5.0.2 on 2024-02-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingredients",
            "0003_alter_ingredient_category_alter_ingredient_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ["name"],
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
    ]
