# Generated by Django 5.0.2 on 2024-06-25 12:44

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_category_alter_ingredient_sort_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(500),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Без категории",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    common.validators.AcceptedSymbolsValidator(
                        "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!№;%:?*()/.,\\«»—–- \"'°+¼½"
                    ),
                ],
                verbose_name="Название",
            ),
        ),
    ]
