name: Deploy backend

on:
  push:
    branches:
      - master
      - dev
      - ci_v3
  #push:
    #branches: 
      #- master
      #- dev
      #- edit-ci-cd
    #tags: 
    #  - 'releases-*'

  #pull_request_review:
  #  types:
  #    - submitted
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-back-to-prod:
    if: ${{ github.ref == 'master' }}
    runs-on: [self-hosted, linux, firstvds]
    environment: prod
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      - name: Git & Docker
        env: 
          PROJECT_FOLDER: ${{ vars.PROJECT_FOLDER }}
          ENV_MENU: ${{ vars.ENV_VAR }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          ENV_STAGE: ${{ vars.ENV_VAR }}
          PORT_NGINX: ${{ vars.PORT_NGINX }}
          GIT_BRANCH: ${{ github.ref }}
        run: |
          echo $PROJECT_FOLDER
          cd $PROJECT_FOLDER
          git pull
          git checkout $GIT_BRANCH
          git pull
          docker compose -f ./infra/docker-compose.back.yml down || true
          docker rmi production-web:latest || true
          docker compose -f ./infra/docker-compose.back.yml up -d
  
  deploy-back-to-dev:
    if: ${{ github.ref == 'dev' || 'ci_v3' }}
    runs-on: [self-hosted, linux, timeweb]
    environment: dev
    steps:
      - name: Build docker images & Run docker-compose
        env: 
          PROJECT_FOLDER: ${{ vars.PROJECT_FOLDER }}
          ENV_MENU: ${{ vars.ENV_VAR }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          ENV_STAGE: ${{ vars.ENV_VAR }}
          PORT_NGINX: ${{ vars.PORT_NGINX }}
          GIT_BRANCH: ${{ github.ref }}
        run: |
          echo $PROJECT_FOLDER
          cd $PROJECT_FOLDER
          git pull
          git checkout $GIT_BRANCH
          git pull
          docker compose -f ./infra/docker-compose.back.yml down || true
          #docker rmi infra-web:latest || true
          docker compose -f ./infra/docker-compose.back.yml up -d