name: Deploy prostoemenu to vds

on:
  push:
    branches: ["Prostoe-menu-deploy"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, firstvds]
    environment: prod
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      - name: Git & Docker
        env: 
          PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
          ENV_MENU: ${{ vars.ENV_VAR }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        run: |
          echo $PROJECT_FOLDER
          cd $PROJECT_FOLDER
          git checkout Prostoe-menu-deploy
          git pull
          docker compose -f docker-compose.prod.yml down || true
          docker compose -f docker-compose.prod.yml up -d