name: Deploy container to Azure Functions App

on:
  push:
    branches: ["Prostoe-menu-deploy"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, firstvds]
    environment: prod
    steps:
    - name: Run command on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.SSH_HOST}}
        user: ${{secrets.SSH_USER}}
        password: ${{secrets.SSH_PASSWORD}}
        command: |
          cd ${{ secrets.PROJECT_FOLDER }};
          git checkout Prostoe-menu-deploy;
          git pull;
          docker compose -f docker-compose.prod.yml down || true;
          docker compose -f docker-compose.prod.yml up -d;