name: Deploy prostoemenu to vds

on:
  push:
    branches: ["Prostoe-menu-deploy"]

permissions:
  contents: read

env:
  USER: ${{secrets.SSH_USER}}
  HOST: ${{secrets.SSH_HOST}}
  PASS: ${{secrets.SSH_PASSWORD}}
  PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
  

jobs:
  deploy:
    runs-on: [self-hosted, linux, firstvds]
    environment: prod
    steps:
    - name: Run command on remote server
      uses: fifsky/ssh-action@master
      with:
        host: '$USER@$HOST'
        pass: $PASS
        command: |
          cd $PROJECT_FOLDER
          git checkout Prostoe-menu-deploy
          git pull
          docker compose -f docker-compose.prod.yml down || true
          docker compose -f docker-compose.prod.yml up -d